apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: trash-2m
  namespace: default
spec:
  schedule: "*/15 * * * *"
  startingDeadlineSeconds: 100
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trash-2m
            image: alpine 
            args:
            - "/bin/sh"
            - "-c"
            - 'find YOUR-PATH/$(date +%Y) -type f -size -2000k -exec rm -f {} \;'
            volumeMounts:
            - name: storage          
              mountPath: /YOUR/PATH
          restartPolicy: OnFailure
          volumes:
          - name: storage
            hostPath:
              path: /YOUR/PATH
              type: Directory

