apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rclone
  namespace: default
spec:
  schedule: "*/30 * * * *"
  startingDeadlineSeconds: 100
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rclone-gdrive
            image: alpine 
            env:
            - name: XDG_CONFIG_HOME
              value: "/YOUR/PATH"
            args:
            - "/bin/sh"
            - "-c"
            - 'apk update; apk add rclone; rclone sync PATH-LOCAL PATH-RCLONE --delete-before --drive-use-trash=false --local-no-check-updated'
            volumeMounts:
            - name: storage          
              mountPath: /YOUR/PATH
            - name: tz-config
              mountPath: /etc/localtime
          restartPolicy: OnFailure
          volumes:
          - name: storage
            hostPath:
              path: /YOUR/PATH
              type: Directory
          - name: tz-config
            hostPath:
              path: /usr/share/zoneinfo/America/Sao_Paulo 
